
# Site settings
url: https://jpconsulting.sg   # change to your domain when connected
baseurl: ""                    # keep empty for root

# Branding
title: JP Digital Consulting
description: Dynamics NAV/Business Central (BC) Upgrades & Implementations
lang: en

# Theme (GitHub Pages supported remote theme)
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation (used in header include)
nav:
  - title: About
    url: /
  - title: Services
    url: /services/
  - title: Projects
    url: /projects/
  - title: Contact
    url: /contact/

# Build
markdown: kramdown
permalink: pretty
